### ISSUE TITLE
assertion error on max_solutions = 0

### ISSUE THREAD

**Issue by guihomework** [ubi-agni/moveit_task_constructor#13]
with version  mtc_demos https://github.com/ubi-agni/mtc_demos/commit/ce67861279678cb10b776d2ebf84b017d2a92b0f  mtc 2bf912d3dfbc8cab1a562c065b439d303b86fb4c

when calling task.plan() without a max_solutions, in mtc_demo iros_grasp, one might get an assertion error.

```
[ INFO] [1551092899.567176168]: Solution found in 1.195480 seconds
[ INFO] [1551092903.420171397]: SimpleSetup: Path simplification took 3.852925 seconds and changed from 4 to 7 states
iros_grasp: moveit_task_constructor/core/src/container.cpp:292: void moveit::task_constructor::SolutionCollector::operator()(const container_type&, double): Assertion `trace.size() <= max_depth' failed.
```

**Comment by rhaschke** [comment]
Fixed in 26f679bd8e9d91dc03e3c7782d390a2f2b92e245
